### ISSUE TITLE
Hata

### ISSUE THREAD

**Issue by orkuncaylar** [inliva/demoCreator#1]
indirip demo oluşturuyorum, zip dosyasından çıkan index.html çalıştırdığım zaman **Demo yüklenirken hata oluştu. Lütfen bizimle iletişime geçiniz** diye hata alıyorum Cihad bey bi kontrol eder misiniz ?

Ellerinize sağlık bu arada çalışan versiyon gerçekten çok iyi.

**Comment by cihadgunduz** [comment]
file:// protokolünde erişim sağlıyorsan hata alman normal. http:// şeklinde erişmen gerekiyor. localhost veya bir sunucuda çalıştırmalısın.
